<?php
$root = __DIR__;
$content = getenv('PAGECORE_SAMPLE_CONTENT') ?: $root . '/working-content';
$uploads = getenv('PAGECORE_SAMPLE_UPLOADS') ?: $root . '/working-uploads';
$siteUrl = getenv('PAGECORE_SITE_URL') ?: 'http://127.0.0.1:8765';

return array(
    'development_only' => true,
    'demo_credentials' => true,
    'session_name' => 'PAGECORE_SAMPLE',
    'session_hours' => 8,
    'require_https' => false,
    'cookie_secure' => false,
    'hsts' => false,
    'trusted_proxies' => array(),
    'username' => 'admin',
    'password_hash' => '$2y$12$oWLexpCUtOum0KYLB0Ms/ukXgxPm0XepSJNAY8j.oZ8qldfdxpl9W',
    'login_rate_limit_dir' => $content . '/.state',
    'login_rate_window_seconds' => 300,
    'login_rate_source_limit' => 5,
    'login_rate_account_limit' => 10,
    'audit_enabled' => true,
    'audit_log_path' => $content . '/.state/audit.jsonl',
    'audit_max_bytes' => 5242880,
    'content_dir' => $content,
    'backup_dir' => $content . '/.backups',
    'backup_keep' => 20,
    'site_root' => $root,
    'site_url' => $siteUrl,
    'site_name' => 'Pagecore Sample',
    'base_url' => '/sample-site',
    'cms_url' => '/cms',
    'uploads_dir' => $uploads,
    'uploads_url' => '/sample-site/working-uploads',
    'max_upload_mb' => 8,
    'max_request_bytes' => 8912896,
    'max_content_bytes' => 262144,
    'max_nav_bytes' => 32768,
    'max_metadata_bytes' => 4096,
    'max_title_bytes' => 255,
    'max_identifier_bytes' => 512,
    'max_query_bytes' => 256,
    'max_image_width' => 4096,
    'max_image_height' => 4096,
    'max_image_pixels' => 16000000,
    'max_upload_storage_bytes' => 16777216,
    'max_upload_files' => 2000,
    'max_uploads_per_month' => 20,
    'media_page_size' => 24,
    'max_media_page_size' => 50,
    'max_inventory_page_size' => 100,
    'max_inventory_items' => 150,
    'max_template_files' => 100,
    'template_roots' => array('index.php', 'showcase.php', 'contact.php', 'post.php', 'news', 'search'),
    'max_search_query_bytes' => 100,
    'max_search_index_bytes' => 5242880,
    'max_search_index_items' => 5000,
    'max_search_results' => 100,
    'search_results_per_page' => 10,
    'allowed_ext' => array('jpg', 'jpeg', 'png', 'gif', 'webp', 'pdf'),
    'post_url' => '/sample-site/post/{slug}/',
    'categories' => array(
        'news' => array('News', '/sample-site/news/'),
        'events' => array('Events', '/sample-site/news/?category=events'),
        'docs' => array('Docs', '/sample-site/news/?category=docs'),
    ),
    'search_pages' => array(
        '/sample-site/' => array('Home', 'Page', 'home/hero'),
        '/sample-site/news/' => array('News', 'Listing', null),
        '/sample-site/showcase/' => array('Showcase', 'Page', 'showcase/intro'),
        '/sample-site/contact.php' => array('Contact', 'Page', 'contact/body'),
    ),
    'sitemap_extra_routes' => array('/sample-site/search/', '/sample-site/contact.php'),
    'static_media_references' => array('/sample-site/assets/sample-diagram.svg'),
);
