<?php
require dirname(__DIR__) . '/_bootstrap.php';

$indexFile = __DIR__ . '/../search-index.json';
if (!is_file($indexFile)) {
    cms_regenerate_indexes();
}
$items = is_file($indexFile) ? json_decode(file_get_contents($indexFile), true) : array();
if (!is_array($items)) { $items = array(); }

$query = trim(isset($_GET['q']) ? (string) $_GET['q'] : '');
$results = array();
foreach ($items as $item) {
    $haystack = strtolower(($item['t'] ?? '') . ' ' . ($item['k'] ?? '') . ' ' . ($item['e'] ?? ''));
    if ($query === '' || strpos($haystack, strtolower($query)) !== false) {
        $results[] = $item;
    }
}

sample_header('Search');
?>
<main>
  <section class="page-title">
    <p class="eyebrow">Generated index</p>
    <h1>Search content regenerated by the CMS</h1>
  </section>
  <section class="band">
    <form class="search-form" method="get" action="<?= sample_url('/search/') ?>">
      <label for="q">Search sample content</label>
      <div>
        <input id="q" name="q" value="<?= htmlspecialchars($query, ENT_QUOTES, 'UTF-8') ?>" placeholder="Try news, workflow, contact">
        <button type="submit">Search</button>
      </div>
    </form>
    <div class="search-results">
      <?php foreach ($results as $item): ?>
        <article class="post-card">
          <p class="eyebrow"><?= htmlspecialchars($item['k'] ?? '', ENT_QUOTES, 'UTF-8') ?></p>
          <h3><a href="<?= htmlspecialchars($item['u'] ?? '#', ENT_QUOTES, 'UTF-8') ?>"><?= htmlspecialchars($item['t'] ?? '', ENT_QUOTES, 'UTF-8') ?></a></h3>
          <p><?= htmlspecialchars($item['e'] ?? '', ENT_QUOTES, 'UTF-8') ?></p>
        </article>
      <?php endforeach; ?>
      <?php if (!$results): ?>
        <p>No matching content.</p>
      <?php endif; ?>
    </div>
  </section>
</main>
<?php sample_footer(); ?>
