<?php
// Production example. Keep this file outside the document root after copying it.
$private = '/srv/pagecore';
return array(
    'development_only' => false,
    'demo_credentials' => false,
    'session_name' => 'PAGECORE_ADMIN',
    'session_hours' => 8,
    'require_https' => true,
    'cookie_secure' => true,
    'hsts' => true,
    'trusted_proxies' => array('10.0.0.10'),
    'username' => 'admin',
    'password_hash' => '$2y$12$replace.with.a.password_hash.value.before.use',
    'login_rate_limit_dir' => $private . '/state/login',
    'login_rate_window_seconds' => 300,
    'login_rate_source_limit' => 5,
    'login_rate_account_limit' => 10,
    'audit_enabled' => true,
    'audit_log_path' => $private . '/state/audit.jsonl',
    'audit_max_bytes' => 5242880,
    'content_dir' => $private . '/content',
    'backup_dir' => $private . '/backups',
    'backup_keep' => 20,
    'site_root' => '/var/www/example/public',
    'site_url' => 'https://www.example.com',
    'site_name' => 'Example site',
    'base_url' => '/',
    'cms_url' => '/cms',
    'uploads_dir' => $private . '/uploads',
    'uploads_url' => '/cms/media-file.php?path=',
    'max_upload_mb' => 8,
    'max_request_bytes' => 8912896,
    'max_content_bytes' => 262144,
    'max_nav_bytes' => 32768,
    'max_metadata_bytes' => 4096,
    'max_title_bytes' => 255,
    'max_identifier_bytes' => 512,
    'max_query_bytes' => 256,
    'max_image_width' => 4096,
    'max_image_height' => 4096,
    'max_image_pixels' => 16000000,
    'max_upload_storage_bytes' => 268435456,
    'max_upload_files' => 2000,
    'max_uploads_per_month' => 200,
    'media_page_size' => 24,
    'max_media_page_size' => 50,
    'max_inventory_page_size' => 100,
    'max_inventory_items' => 5000,
    'max_search_query_bytes' => 100,
    'max_search_index_bytes' => 5242880,
    'max_search_index_items' => 5000,
    'max_search_results' => 100,
    'search_results_per_page' => 10,
    'allowed_ext' => array('jpg', 'jpeg', 'png', 'gif', 'webp', 'pdf'),
    'post_url' => '/post/{slug}/',
    'categories' => array('news' => array('News', '/news/')),
    'search_pages' => array('/' => array('Home', 'Page', 'home/main')),
    'sitemap_extra_routes' => array('/search/', '/contact/'),
);
